run:
  timeout: 10m
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - copyloopvar # requires Go 1.22
    - cyclop
    - decorder
    # - depguard # a list of acceptable packages is necessary to use this
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - execinquery # deprecated since v1.58.0
    - exhaustive
    # - exhaustruct # anoying
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox # "TODO" is allowed
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - gomnd # deprecated since v1.58.0
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    # - intrange # requires Go 1.22
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn # annoying
    - noctx
    - nolintlint
    # - nonamedreturns # Named returns can be necessary sometimes
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen # needs tuning
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl # anoying
    - zerologlint

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment ## temporally disabled
      - shadow ## temporally disabled
  goheader:
    values:
      regexp:
        date: "20[1-2][0-9]"
    template: |-
      Copyright {{date}} The Swarm Authors. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
  paralleltest:
    # Ignore missing calls to `t.Parallel()` and only report incorrect uses of `t.Parallel()`.
    ignore-missing: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
    - path: version\.go
      linters:
        - gochecknoglobals
    - linters:
        - goheader
      text: "go-ethereum Authors" ## disable check for other authors
    - path: _test\.go
      linters:
        - goconst ## temporally disable goconst in test
    - linters:
        - forbidigo
      path: cmd/bee/cmd
      text: "use of `fmt.Print"   ## allow fmt.Print in cmd directory
    - linters:
        - dogsled
      path: pkg/api/(.+)_test\.go # temporally disable dogsled in api test files
    - linters:
        - dogsled
      path: pkg/pushsync/(.+)_test\.go # temporally disable dogsled in pushsync test files
      # temporally disable paralleltest in following packages
    - linters:
        - paralleltest
      path: pkg/postage
    - linters:
        - paralleltest
      path: pkg/log
    - linters:
        - paralleltest
      path: pkg/statestore
    - linters:
        - paralleltest
      path: pkg/storer
    - linters:
        - paralleltest
      path: pkg/storage
  exclude-files:
    - ".*generated.*\\.go$"
    - ".*\\.pb\\.go"
    - "asdf.*"
  exclude-use-default: false
  max-issues-per-linter: 0
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: false
  show-stats: true
  uniq-by-line: false
  sort-results: true
  sort-order:
    - file # filepath, line, and column.
    - linter
    - severity
severity:
  default-severity: error
  rules:
    - linters:
        - revive
      severity: warning
    - linters:
        - lll
      severity: info
